export interface Task {
  id: string; // Unique identifier for the task
  description: string; // Detailed description of the task
  assignedAssistant: string; // ID of the assistant assigned to this task
  status: 'pending' | 'in_progress' | 'completed' | 'failed'; // Task status
  inputData?: string | null; // Input data for the task
  outputData?: string | null; // Output data generated by the task
  createdAt: Date; // Task creation timestamp
  updatedAt: Date; // Task last update timestamp
}
export interface TaskRow {
  id: string; // Unique identifier for the task
  description: string; // Detailed description of the task
  assigned_assistant: string; // ID of the assistant assigned to this task
  status: 'pending' | 'in_progress' | 'completed' | 'failed'; // Task status
  input_data?: string | null; // Record<string, unknown>; // Input data for the task
  output_data?: string | null; // Record<string, unknown>; // Output data generated by the task
  created_at: Date; // Task creation timestamp
  updated_at: Date; // Task last update timestamp
}
