export interface Task {
  id: string; // Unique identifier for the task
  description: string; // Task description
  tags: string[]; // Tags related to the task (e.g., "html", "responsive")
  assignedAssistant: string; // ID of the assigned assistant
  status: 'pending' | 'in_progress' | 'completed' | 'failed'; // Task status
  inputData: Record<string, unknown>; // Input for the task
  outputData?: Record<string, unknown>; // Output generated by the assistant
  feedback?: string; // Optional feedback for the task
  createdAt: Date; // Task creation timestamp
  updatedAt: Date; // Last update timestamp
}
