import express from 'express';
import swaggerUi from 'swagger-ui-express';
import swaggerJSDoc from 'swagger-jsdoc';
import dotenv from 'dotenv';
import { getDb } from './database/database';
import { generateApiDocs } from './generate-doc';
import { generateSwaggerPaths } from './swaggerHelper';
import { homePageHandler } from './homepage';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { RegisterRoutes } from './routes'; // auto-generated by tsoa
import swaggerDocument from './swagger.json'; // auto-generated by tsoa

dotenv.config(); // Load environment variables

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

// Allow requests from your Angular app
app.use(
  cors({
    origin: 'http://localhost:4200',
    methods: ['GET', 'POST', 'PUT', 'DELETE'],
    allowedHeaders: ['Content-Type', 'Authorization'],
  })
);

// Database initialization
async function startServer() {
  try {
    // Swagger setup
    const apiDocs = generateApiDocs();
    const swaggerPaths = generateSwaggerPaths(apiDocs);

    const swaggerOptions = {
      definition: {
        openapi: '3.0.0',
        info: {
          title: 'API Documentation',
          version: '1.0.0',
          description: 'API documentation for my application',
        },
        paths: swaggerPaths,
      },
      apis: ['./routes/*.ts', './controllers/*.ts'],
    };

    const swaggerSpec = swaggerJSDoc(swaggerOptions);
    // Register TSOA-generated routes and docs (new features)
    // NOTE: assumes TSOA has generated `src/routes` and `src/swagger.json`
    try {
      RegisterRoutes(app);
    } catch (err) {
      console.warn('⚠️ Failed to register TSOA routes (RegisterRoutes):', err);
    }

    // Serve TSOA-generated OpenAPI at /api-docs
    try {
      app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
    } catch (err) {
      console.warn('⚠️ Failed to mount TSOA swagger document at /api-docs:', err);
      // Fallback to legacy generated swagger if available
      app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
    }

    // Keep legacy swagger generation for old features at /api-docs-legacy
    app.use('/api-docs-legacy', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
    app.get('/', homePageHandler);

    await createRoutes();
    console.log('Routes Initialized: ');

    app.listen(Number(PORT), '0.0.0.0', () => {
      console.log(`Server is running at http://localhost:${PORT}`);
    });
  } catch (error) {
    console.error('Error initializing database:', error);
    process.exit(1);
  }
}

// 🔥 Function to create and attach routes AFTER DB is ready
async function createRoutes() {
  const db = getDb();
  db.setFeedbackEnabled(true);
  await db.initialize();
  console.log('Database initialized successfully.');

  // ✅ Legacy manual routes
  const assistantRoutes = (await import('./routes/assistant.routes')).default;
  const feedbackRoutes = (await import('./routes/feedback.routes')).default;
  const memoryExtraRoutes = (await import('./routes/memory-extra.routes')).default;
  const memoryFocusRuleRoutes = (await import('./routes/memory-focus-rule.routes')).default;
  const memoryFocusedRoutes = (await import('./routes/memory-focused.routes')).default;
  const memoryOwnedRoutes = (await import('./routes/memory-owned.routes')).default;
  const memoryRoutes = (await import('./routes/memory.routes')).default;
  const promptRoutes = (await import('./routes/prompt.routes')).default;
  const orchestratorRoutes = (await import('./routes/orchestrator.routes')).default;
  const relationshipGraphRoutes = (await import('./routes/relationship-graph.routes')).default;
  const tagExtraRoutes = (await import('./routes/tag-extra.routes')).default;
  const tagRoutes = (await import('./routes/tag.routes')).default;
  const taskRoutes = (await import('./routes/task.routes')).default;
  const backupRoutes = (await import('./routes/backup.routes')).default;
  const assistantMemoryRoutes = (await import('./routes/assistant-memory.routes')).default;

  const chatmessagesRoutes = (await import('./routes/chat-messages.routes')).default;
  const chatsRoutes = (await import('./routes/chats.routes')).default;
  const sessionsRoutes = (await import('./routes/sessions.routes')).default;
  const conversationRoutes = (await import('./routes/conversation.routes')).default;

  app.use('/backup', backupRoutes);
  app.use('/orchestrator', orchestratorRoutes);
  app.use('/assistant', assistantRoutes);
  app.use('/feedback', feedbackRoutes);
  app.use('/memory-extra', memoryExtraRoutes);
  app.use('/memory-focus-rule', memoryFocusRuleRoutes);
  app.use('/memory-focused', memoryFocusedRoutes);
  app.use('/memory-owned', memoryOwnedRoutes);
  app.use('/memory', memoryRoutes);
  app.use('/prompt', promptRoutes);
  app.use('/relationship-graph', relationshipGraphRoutes);
  app.use('/tag-extra', tagExtraRoutes);
  app.use('/tag', tagRoutes);
  app.use('/task', taskRoutes);
  app.use('/assistant-memory', assistantMemoryRoutes);
  app.use('/chat-messages', chatmessagesRoutes);
  app.use('/chats', chatsRoutes);
  app.use('/sessions', sessionsRoutes);
  app.use('/conversation', conversationRoutes);

  // ✅ NEW FEATURE SYSTEM (no glob)
  const featuresDir = path.join(__dirname, 'features');
  if (fs.existsSync(featuresDir)) {
    const featureDirs = fs.readdirSync(featuresDir, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name);

    for (const dir of featureDirs) {
      const tsIndex = path.join(featuresDir, dir, 'index.ts');
      const jsIndex = path.join(featuresDir, dir, 'index.js');
      let fileToLoad: string | null = null;

      if (fs.existsSync(tsIndex)) fileToLoad = tsIndex;
      else if (fs.existsSync(jsIndex)) fileToLoad = jsIndex;

      if (!fileToLoad) {
        console.log(`ℹ️ No index.ts/js in ${dir}, skipping`);
        continue;
      }

      try {
        const mod = await import(fileToLoad);
        const feature = mod.default || mod;
        if (feature && typeof feature.registerRoutes === 'function' && feature.name) {
          feature.registerRoutes(app);
          console.log(`✅ Mounted /${feature.name}`);
        } else {
          console.log(`ℹ️ Skipped ${dir} — no valid FeatureModule`);
        }
      } catch (err) {
        console.warn(`⚠️ Failed to load feature ${dir}:`, err);
      }
    }
  }
}

export default app;

if (require.main === module) {
  startServer();
}
